version: "3"
services:
  iptv-proxy2:
    image: alobato/iptv-proxy2:latest
    container_name: iptv-proxy2
    restart: on-failure
    volumes:
      - ../data:/data
    environment:
      M3U_URL: "http://example.com/get.php?username=USER&password=PASS&type=m3u_plus&output=m3u8"
      PORT: 8080
      ADVERTISED_PORT: 443
      HOSTNAME: iptv.proxyexample.xyz
      HTTPS: "1"
      USER: myuser
      PASSWORD: mypass
      JSON_FOLDER: /data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.iptv-proxy2.rule=Host(`iptv.proxyexample.xyz`)"
      - "traefik.http.routers.iptv-proxy2.entrypoints=websecure"
      - "traefik.http.routers.iptv-proxy2.tls.certresolver=mydnschallenge"
      - "traefik.http.services.iptv-proxy2.loadbalancer.server.port=8080"

  traefik:
    image: traefik:v2.4
    restart: always
    read_only: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Traefik/traefik.yaml:/traefik.yaml:ro
      - ./Traefik/etc/traefik:/etc/traefik/
      - ./Traefik/log:/var/log/traefik/
